# Pruebas básicas
Una vez vistas las clases por las que está formada gymnasium y de que trata, se van a realizar varias pruebas con un entorno, en concreto CartPole para ver el funcionamiento general de la librería y sus posibilidades. <br>

El entorno *CartPole*, cumple las siguientes características:
- **Espacio de acciones** 
    0. para mover el carro a la izquierda
    1. para mover el carro a la derecha
- **Espacio de observaciones**:
    0. Posición del carro
    1. Velocidad del carro
    2. Ángulo del palo
    3. Velocidad angular del palo
    
La misión del entorno, es mantener el palo encima del carro el máximo tiempo posible.

En esta primera prueba, las acciones que se van a tomar van a ser random, es decir, no se va a seguir ninguna política ni ningún tipo de entrenamiento. Este ejemplo, es únicamente para ver como sería una salida típica.

In [1]:
import gymnasium as gym
env = gym.make("CartPole-v1", render_mode="human")
observation, info = env.reset() #primer reset necesario

total = 0

for episode in range(20):
    observation, info = env.reset()
    for t in range(1000): #tiempo que está en ejecución el entorno
        action = env.action_space.sample() #accion random
        observation, reward, terminated, truncated, info = env.step(action)

        if terminated or truncated: #finalizada la ejecución del anterior
            observation, info = env.reset()
            total += (t+1)
            print("Episodio terminado después de {} timesteps".format((t+1)))
            break
            
print("Tiempo medio: {}".format(total/20))
env.close()

/home/alberto/anaconda3/envs/gymnasium/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/alberto/anaconda3/envs/gymnasium/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:249: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


Episodio terminado después de 10 timesteps
Episodio terminado después de 35 timesteps
Episodio terminado después de 16 timesteps
Episodio terminado después de 11 timesteps
Episodio terminado después de 23 timesteps
Episodio terminado después de 19 timesteps
Episodio terminado después de 35 timesteps
Episodio terminado después de 17 timesteps
Episodio terminado después de 12 timesteps
Episodio terminado después de 19 timesteps
Episodio terminado después de 24 timesteps
Episodio terminado después de 23 timesteps
Episodio terminado después de 14 timesteps
Episodio terminado después de 35 timesteps
Episodio terminado después de 32 timesteps
Episodio terminado después de 28 timesteps
Episodio terminado después de 57 timesteps
Episodio terminado después de 42 timesteps
Episodio terminado después de 67 timesteps
Episodio terminado después de 18 timesteps
Tiempo medio: 26.85


Una posible política para este problema sería que el palo intentase estar centrado, ya que la meta es mantenerse el máximo tiempo posible. Para ello, si el palo es mayor que 0, se estará cayendo a la derecha por lo que habrá que mover el carro a la derecha también. Un ejemplo de implementación sería:

In [2]:
import gymnasium as gym
env = gym.make("CartPole-v1", render_mode="human")
observation, info = env.reset() 

total = 0

for episode in range(20):
    observation, info = env.reset()
    for t in range(1000): 
        if observation[2] > 0.0:
            observation, reward, terminated, truncated, info = env.step(1)
        else:
            observation, reward, terminated, truncated, info = env.step(0)

        if terminated or truncated: 
            observation, info = env.reset()
            total += (t+1)
            print("Episodio terminado después de {} timesteps".format((t+1)))
            break
            
print("Tiempo medio: {}".format(total/20))
env.close()





Episodio terminado después de 39 timesteps
Episodio terminado después de 34 timesteps
Episodio terminado después de 50 timesteps
Episodio terminado después de 34 timesteps
Episodio terminado después de 48 timesteps
Episodio terminado después de 44 timesteps
Episodio terminado después de 39 timesteps
Episodio terminado después de 25 timesteps
Episodio terminado después de 59 timesteps
Episodio terminado después de 25 timesteps
Episodio terminado después de 43 timesteps
Episodio terminado después de 37 timesteps
Episodio terminado después de 46 timesteps
Episodio terminado después de 35 timesteps
Episodio terminado después de 35 timesteps
Episodio terminado después de 41 timesteps
Episodio terminado después de 53 timesteps
Episodio terminado después de 54 timesteps
Episodio terminado después de 49 timesteps
Episodio terminado después de 45 timesteps
Tiempo medio: 41.75


Después de esta ejecución, se puede comprobar que se duplica el tiempo medio que aguanta el palo, por lo que la política escogida sería correcta. <br> <br>

Otra forma de posible, sería que además del ángulo, también la velocidad angular (*observation[3]*) sea positiva, ya que en casos en los que este prácticamente equilibrado, se haría un movimiento que podría ser innecesario. Un ejemplo de esta política sería:

In [3]:
import gymnasium as gym
env = gym.make("CartPole-v1", render_mode="human")
observation, info = env.reset() 

total = 0

for episode in range(20):
    observation, info = env.reset()
    for t in range(1000): 
        if observation[2] > 0.0 and observation[3] > 0.0:
            observation, reward, terminated, truncated, info = env.step(1)
        else:
            observation, reward, terminated, truncated, info = env.step(0)

        if terminated or truncated: 
            observation, info = env.reset()
            total += (t+1)
            print("Episodio terminado después de {} timesteps".format((t+1)))
            break
            
print("Tiempo medio: {}".format(total/20))
env.close()


Episodio terminado después de 113 timesteps
Episodio terminado después de 272 timesteps
Episodio terminado después de 160 timesteps
Episodio terminado después de 189 timesteps
Episodio terminado después de 151 timesteps
Episodio terminado después de 230 timesteps
Episodio terminado después de 130 timesteps
Episodio terminado después de 193 timesteps
Episodio terminado después de 113 timesteps
Episodio terminado después de 128 timesteps
Episodio terminado después de 134 timesteps
Episodio terminado después de 113 timesteps
Episodio terminado después de 186 timesteps
Episodio terminado después de 107 timesteps
Episodio terminado después de 184 timesteps
Episodio terminado después de 106 timesteps
Episodio terminado después de 188 timesteps
Episodio terminado después de 195 timesteps
Episodio terminado después de 137 timesteps
Episodio terminado después de 191 timesteps
Tiempo medio: 161.0


In [4]:
env.close()

Para aplicar Q-learning a este problema continuo, sería neceario discretizarlo para poder formar la tabla. Al ser un proceso que no tiene que ver con el uso y funcionamiento de la librería, se va a aplicar este algoritmo con un problema con espacio de observaciones discreto (*Frozen Lake*), para demostrar un caso de uso de Aprendizaje Reforzado combinado con la librería.<br> <br>

Las características de este entorno son:
- **Espacio de acciones** 
    0. Moverse a la izquierda
    1. Moverse a la derecha
    2. Moverse hacia arriba
    3. Moverse hacia abajo
- **Espacio de observaciones**:
    0. Valor representado por: $fila\_actual*nfilas + columna\_actual$ (empezando ambas desde 0). Por ejemplo, la posición 4x4 sería: $3*4 + 3 = 15$

In [4]:
import numpy as np
import gymnasium as gym
import random


env = gym.make("FrozenLake-v1")
action_size = env.action_space.n
state_size = env.observation_space.n

qtable = np.zeros((state_size, action_size))
print(qtable)

total_episodes = 15000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005             # Exponential decay rate for exploration prob


# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, truncated, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

/home/alberto/anaconda3/envs/gymnasium/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


/home/alberto/anaconda3/envs/gymnasium/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:249: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


ValueError: too many values to unpack (expected 4)